name: Decision
description: |
  辅助决策子平台是一个支撑科学决策的信息平台，通过汇集政府数据、互联网数据、运营商数据开展数据分析和建立基础模型算法，针对经济发展、民生服务、城市安全、环境治理等重点业务领域建立辅助决策模型，利用统计分析、数据挖掘建模及人工智能等技术，进行模块化分析，为决策者提供更为系统、精确、科学的参考依据，推动政府经验决策向科学决策转变。
version: v0.1
category: 智慧院