version: '2'
catalog:
  name: "Pandu"
  version: "v1.1"
  description: "面向上层应用提供包含自动化、智能化的工具包和中间件的集成化环境，实现个性化业务应用的高效开发管理。"
  uuid: cetc-pandu-1
  questions:
    - variable: server_port
      description: "服务端口"
      label: "服务端口"
      required: true
      default: "8090"
      type: int
    - variable: mysql_service
      description: "数据库服务"
      label: "数据库服务"
      required: true
      default: "mysql/mysql"
      type: "service"
services:
  tb:
    scale: 1
    retain_ip: true
    health_check:
      port: 8090
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
