name: Moniwa
description: |
  监测预警子平台通过整合各委办局数据、互联网数据、物联专网感知数据，应用地理信息系统技术（GIS）上图，实现对大兴区城市设施、公共安全、民生服务、生态环境、经济发展等重点领域运行状况的展现，通过数据关联融合形成城市管理服务关键体征指标体系，全面呈现城市管理与服务的综合态势，感知风险和发展趋势，便于领导及各综合部门全面掌握城市的运行状况。
version: v0.1
category: 智慧院